services:
  mongo:
    image: mongo:8
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports: ["27017:27017"]
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 20
  mongo-init:
    image: mongo:8
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    command:
      [
        "mongosh",
        "--host",
        "mongo:27017",
        "--eval",
        "rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]})",
      ]
  api:
    build: ./backend
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/household?replicaSet=rs0
    ports: ["4000:4000"]
    depends_on:
      mongo-init:
        condition: service_completed_successfully
